numerik.pdf: numerik.tex vorlesung2014-10-13.tex vorlesung2014-10-16.tex vorlesung2014-10-20.tex vorlesung2014-10-23.tex vorlesung2014-10-27.tex vorlesung2014-10-30.tex vorlesung2014-11-03.tex vorlesung2014-11-06.tex vorlesung2014-11-10.tex vorlesung2014-11-13.tex vorlesung2014-11-17.tex vorlesung2014-11-20.tex vorlesung2014-11-24.tex vorlesung2014-11-27.tex
	pdflatex numerik.tex
	pdflatex numerik.tex

clean:
	rm -f  *~ *.aux *.log *.out *.toc *.backup
